# on:
#   # Trigger analysis when pushing in master or pull requests, and when creating
#   # a pull request. 
#   push:
#     branches:
#       - master
#   pull_request:
#       types: [opened, synchronize, reopened]
# name: Main Workflow
# jobs:
#   sonarcloud:
#     runs-on: ubuntu-latest
#     steps:
#     - uses: actions/checkout@v2
#     - name: SonarCloud Scan
#       uses: sonarsource/sonarcloud-github-action@master
#       env:
#         SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
#         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
