# This is a basic workflow to help you get started with Actions

name: Update EKS Configuration

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # # Runs a single command using the runners shell
    # - name: Push config to EKS Cluster
    #   run: |
    #     aws configure set default.region us-east-1
    #     aws configure set default.output json
    #     aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
    #     aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    #     aws configure set aws_session_token ${{ secrets.AWS_SESSION_TOKEN }}
    #     sed -i "s#IMAGE_NAME#antoineguillard/juiceshop#g" kustomization.yaml
    #     sed -i "s/IMAGE_TAG/sha-$(git rev-parse --short HEAD)/g" kustomization.yaml
    #     aws eks update-kubeconfig --name isen
    #     kubectl kustomize . | kubectl apply -f -